import Head from "next/head"
import Hero from "../components/Hero"
import Blogs from "../components/blogs/Blogs"
import News from "../components/news/News"

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Blogs />
      <News />
    </div>
  )
}

export default Home
